server.port: 8081

spring:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/albums?useSSL=false
    username: root

security:
    basic:
        enabled: false

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: TP0HQC13TU4PYHFNE1FP
  secretKey: PsGM3ssn0pJCt48+hGKIMzprTgg0ZlfH/zEYxFLH
  bucketName: moviefun
  endpointUrl: http://127.0.0.1:9000
