spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

security:
    basic:
        enabled: false

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: TP0HQC13TU4PYHFNE1FP
  secretKey: PsGM3ssn0pJCt48+hGKIMzprTgg0ZlfH/zEYxFLH
  bucketName: moviefun
  endpointUrl: http://127.0.0.1:9000

albums:
  url: http://localhost:8081/albums
movies:
  url: http://localhost:8082/movies