spring:
  application:
    name: movie-service
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

security:
  basic:
    enabled: false
